### ISSUE TITLE
Correlate the information on monitors

### ISSUE THREAD

**Issue by JTOne123** [emoacht/SdrTest#1]
Hi,
I really appriciate for this repo, it's so good 🙌, thank you so much!

From my understanding you are having a deep understanding of this matter.

**I'm wondering if you could advise me how can I use it on Win 10 17763+?**
[var displayInfo = DisplayInformationInterop.GetForMonitor(monitorHandle);](https://github.com/emoacht/SdrTest/blob/f12c23d487ca1f3536253810cf098bcfc7659963/src/DisplayInfo.Winui/MainWindow.xaml.cs#L31)

What the general approach should be here?

FYI: here is my original question on  [stackoverflow](https://stackoverflow.com/questions/78373635/this-is-a-way-to-get-the-screenheightinrawpixels-rawpixelsperviewpixel-diagona)

Thank you

**Comment by emoacht** [comment]
You can't because the OS does not support it.

Having said that, regarding your question on SO, you can get similar information from [Windows.Devices.Display.DisplayMonitor](https://learn.microsoft.com/ja-jp/uwp/api/windows.devices.display). See [my answer](https://stackoverflow.com/a/74675625/3137337) on SO.

**Comment by JTOne123** [comment]
@emoacht , Thank you for your quick reply,

I've already tried this approach and it looks promising, but I don't know how to find the monitor that my window belongs to. (I did mention that in my stackoverflow question)

Do you know how?

**Comment by emoacht** [comment]
You can get device instance ID of a monitor and it will enable you to identify the monitor whose device instance ID matches.

**Comment by JTOne123** [comment]
@emoacht Yes, it sounds kinda simple, but I can't correlate it.

what do I miss?

![image](https://github.com/emoacht/SdrTest/assets/3457140/4d49272b-a6ff-41c9-af2a-f486095f6fff)

**Comment by emoacht** [comment]
What are you asking? Could you be more specific?

**Comment by emoacht** [comment]
A part of monitor2.DeviceId which starts with "DISPLAY" is the device instance ID.

**Comment by JTOne123** [comment]
@emoacht 

I have an application window, as shown in the first line of my screenshot. I need to identify the monitor where this window is displayed. For instance, if I have two monitors and my application window is on the second one, I need to select **monitor 2**.

Next, I need to determine the physical characteristics of this monitor.

For obtaining the physical characteristics, I can use the API mentioned in your [StackOverflow post](https://stackoverflow.com/questions/54659859/how-can-i-get-the-correct-dpi-of-my-screen-in-wpf/74675625#74675625).

However, I'm having trouble distinguishing the monitor displaying my application window from the others because all the IDs are diffrent, diffrent by form and type.

You suggested using `monitor2.DeviceId`, which is fine, but I can't find any similar properties in either the `window` or `monitor` objects to filter it out.

**Comment by emoacht** [comment]
I posted the [answer](https://stackoverflow.com/a/78395262/3137337) in SO.

**Comment by JTOne123** [comment]
Thank you so much that exactly what I was looking for.
